# Generated by Django 2.0.12 on 2019-12-18 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20191218_0713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='regularpizza',
            name='price_large',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='regularpizza',
            name='price_small',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sicilianpizza',
            name='price_large',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='sicilianpizza',
            name='price_small',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='topping',
            name='rate',
            field=models.FloatField(),
        ),
    ]
