# Generated by Django 2.0.12 on 2019-12-18 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_auto_20191218_0719'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=64)),
                ('item_name', models.CharField(max_length=64)),
                ('item_price', models.FloatField()),
                ('item_quantity', models.IntegerField()),
                ('sub_total', models.FloatField(blank=True)),
            ],
        ),
    ]
