# Generated by Django 2.0.12 on 2019-12-18 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_auto_20191218_1830'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='item_quantity',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='sub_total',
        ),
    ]
